In [1]:
# First, let's load the provided dataset to understand its structure and content.
import pandas as pd

In [4]:
# Load the dataset
file_path_DO = '../Dataset/SurveyData/SurveyData_CSV_DAP_2021_AFUS_dog_owner_v1.0.csv'
df_DO = pd.read_csv(file_path_DO, delimiter=',')  # Assuming tab-delimited format based on the file extension
df_DO

/var/folders/zd/3_6frj8s08b9zb1f3y0xqr2r0000gn/T/ipykernel_7600/3611915152.py:3: DtypeWarning: Columns (36,38,40,42,44,46,48,50,52,54,56,67,70,73,74,75,80,99,195,199,202,207,209,212,348,354,360,366,521,561,735,743) have mixed types. Specify dtype option on import or set low_memory=False.
  df_DO = pd.read_csv(file_path_DO, delimiter=',')  # Assuming tab-delimited format based on the file extension

,dog_id,owner_id,afus_complete_date,afus_dd_dog_weight_lbs,afus_dd_insurance_yn,afus_dd_insurance_company,afus_dd_insurance_company_other,afus_dd_activities_companion_animal,afus_dd_activities_obedience,afus_dd_activities_show,...,afus_oc_secondary_residence_change,afus_oc_secondary_residence_change_date,afus_oc_secondary_residence_ownership,afus_oc_secondary_residence_ownership_other_description,afus_oc_secondary_residence_state,afus_oc_secondary_residence_time_percentage,afus_od_age_range_years,afus_od_max_education,afus_od_max_education_other_description,afus_od_annual_income_range_usd
0,68063,9427,2021-10-24,14.0,True,6.0,NaN,1.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,3.0,98.0,I prefer not to answer,98.0
1,54147,10321,2021-10-15,110.0,False,NaN,NaN,1.0,2.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,5.0,5.0,NaN,7.0
2,58831,18537,2021-11-07,72.0,False,NaN,NaN,1.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,6.0,98.0,Registered dietitian,5.0
3,80304,23529,2021-12-28,18.0,False,NaN,NaN,1.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,6.0,98.0,"Registered Nursing license, and religious ordi...",98.0
4,51443,20124,2021-12-06,16.0,False,NaN,NaN,1.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,6.0,8.0,NaN,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15715,29649,3198,2021-08-19,76.0,True,6.0,NaN,1.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,6.0,5.0,NaN,5.0
15716,79295,19482,NaN,63.0,False,NaN,NaN,1.0,2.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15717,6474,12365,2021-10-13,76.0,True,99.0,NaN,1.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,5.0,8.0,NaN,4.0
15718,78391,16866,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15719,2375,1764,2021-08-11,15.0,False,NaN,NaN,1.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,6.0,7.0,NaN,3.0

In [8]:
df_DO[[
    'afus_db_aggression_level_approached_while_eating',
    'afus_db_aggression_level_delivery_workers_at_home',
    'afus_db_aggression_level_familiar_dog_while_eating',
    'afus_db_aggression_level_familiar_dog_while_playing',
    'afus_db_aggression_level_food_taken_away',
    'afus_db_aggression_level_approached_while_eating',
    'afus_db_aggression_level_on_leash_unknown_dog',
    'afus_db_aggression_level_on_leash_unknown_human',
    'afus_db_aggression_level_unknown_aggressive_dog',
    'afus_db_aggression_level_unknown_human_near_yard']]

,afus_db_aggression_level_approached_while_eating,afus_db_aggression_level_delivery_workers_at_home,afus_db_aggression_level_familiar_dog_while_eating,afus_db_aggression_level_familiar_dog_while_playing,afus_db_aggression_level_food_taken_away,afus_db_aggression_level_approached_while_eating,afus_db_aggression_level_on_leash_unknown_dog,afus_db_aggression_level_on_leash_unknown_human,afus_db_aggression_level_unknown_aggressive_dog,afus_db_aggression_level_unknown_human_near_yard
0,0.0,4.0,NaN,NaN,0.0,0.0,1.0,1.0,4.0,4.0
1,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,2.0
2,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
3,0.0,1.0,NaN,NaN,0.0,0.0,1.0,0.0,2.0,3.0
4,0.0,2.0,NaN,NaN,1.0,0.0,3.0,2.0,3.0,2.0
...,...,...,...,...,...,...,...,...,...,...
15715,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
15716,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15717,0.0,0.0,4.0,NaN,0.0,0.0,2.0,2.0,2.0,1.0
15718,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15719,0.0,2.0,NaN,NaN,0.0,0.0,1.0,1.0,2.0,1.0