In [1]:
import pandas as pd
import os
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder

In [10]:
file_path_AFUS = 'Dataset/SurveyData/SurveyData_CSV_DAP_2021_AFUS_dog_owner_v1.0.csv'

In [11]:
df = pd.read_csv(file_path_AFUS)
df

/var/folders/zd/3_6frj8s08b9zb1f3y0xqr2r0000gn/T/ipykernel_63883/186637762.py:1: DtypeWarning: Columns (36,38,40,42,44,46,48,50,52,54,56,67,70,73,74,75,80,99,195,199,202,207,209,212,348,354,360,366,521,561,735,743) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)

,dog_id,owner_id,afus_complete_date,afus_dd_dog_weight_lbs,afus_dd_insurance_yn,afus_dd_insurance_company,afus_dd_insurance_company_other,afus_dd_activities_companion_animal,afus_dd_activities_obedience,afus_dd_activities_show,...,afus_oc_secondary_residence_change,afus_oc_secondary_residence_change_date,afus_oc_secondary_residence_ownership,afus_oc_secondary_residence_ownership_other_description,afus_oc_secondary_residence_state,afus_oc_secondary_residence_time_percentage,afus_od_age_range_years,afus_od_max_education,afus_od_max_education_other_description,afus_od_annual_income_range_usd
0,68063,9427,2021-10-24,14.0,True,6.0,NaN,1.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,3.0,98.0,I prefer not to answer,98.0
1,54147,10321,2021-10-15,110.0,False,NaN,NaN,1.0,2.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,5.0,5.0,NaN,7.0
2,58831,18537,2021-11-07,72.0,False,NaN,NaN,1.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,6.0,98.0,Registered dietitian,5.0
3,80304,23529,2021-12-28,18.0,False,NaN,NaN,1.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,6.0,98.0,"Registered Nursing license, and religious ordi...",98.0
4,51443,20124,2021-12-06,16.0,False,NaN,NaN,1.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,6.0,8.0,NaN,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15715,29649,3198,2021-08-19,76.0,True,6.0,NaN,1.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,6.0,5.0,NaN,5.0
15716,79295,19482,NaN,63.0,False,NaN,NaN,1.0,2.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15717,6474,12365,2021-10-13,76.0,True,99.0,NaN,1.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,5.0,8.0,NaN,4.0
15718,78391,16866,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15719,2375,1764,2021-08-11,15.0,False,NaN,NaN,1.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,6.0,7.0,NaN,3.0

In [12]:
pure_breed_mapping = {
     0: 'Unknown',
     1: 'Affenpinscher',
     2: 'Afghan Hound',
     3: 'Airedale Terrier',
     4: 'Akita',
     5: 'Alaskan Malamute',
     6: 'American English Coonhound',
     7: 'American Eskimo Dog',
     8: 'American Foxhound',
     9: 'American Hairless Terrier',
     10: 'American Leopard Hound',
     11: 'American Pitbull Terrier',
     12: 'American Staffordshire Terrier',
     13: 'American Water Spaniel',
     14: 'Anatolian Shepherd Dog',
     15: 'Appenzeller Sennenhund',
     16: 'Australian Cattle Dog',
     17: 'Australian Kelpie',
     18: 'Australian Shepherd',
     19: 'Australian Stumpy Tail Cattle Dog',
     20: 'Australian Terrier',
     21: 'Azawakh',
     22: 'Barbet',
     23: 'Basenji',
     24: 'Basset Fauve de Bretagne',
     25: 'Basset Hound',
     26: 'Bavarian Mountain Scent Hound',
     27: 'Beagle',
     28: 'Bearded Collie',
     29: 'Beauceron',
     30: 'Bedlington Terrier',
     31: 'Belgian Laekenois',
     32: 'Belgian Malinois',
     33: 'Belgian Sheepdog',
     34: 'Belgian Tervuren',
     35: 'Bergamasco',
     36: 'Berger Picard',
     37: 'Bernese Mountain Dog',
     38: 'Bichon Frise',
     39: 'Biewer Terrier',
     40: 'Black and Tan Coonhound',
     41: 'Bloodhound',
     42: 'Bluetick Coonhound',
     43: 'Boerboel',
     44: 'Bolognese',
     45: 'Border Collie',
     46: 'Border Terrier',
     47: 'Borzoi',
     48: 'Boston Terrier',
     49: 'Bouvier des Flandres',
     50: 'Boxer',
     51: 'Boykin Spaniel',
     52: 'Bracco Italiano',
     53: 'Braque de Bourbonnais',
     54: 'Braque Francais Pyrenean',
     55: 'Briard',
     56: 'Brittany',
     57: 'Broholmer',
     58: 'Brussels Griffon',
     59: 'Bull Terrier',
     60: 'Bulldog',
     61: 'Bullmastiff',
     62: 'Cairn Terrier',
     63: 'Canaan Dog',
     64: 'Cane Corso',
     65: 'Cardigan Welsh Corgi',
     66: 'Carolina Dog',
     67: 'Catahoula Leopard Dog',
     68: 'Caucasian Shepherd Dog',
     69: 'Cavalier King Charles Spaniel',
     70: 'Central Asian Shepherd Dog',
     71: 'Cesky Terrier',
     72: 'Chesapeake Bay Retriever',
     73: 'Chihuahua',
     74: 'Chinese Crested',
     75: 'Chinese Shar-Pei',
     76: 'Chinook',
     77: 'Chow Chow',
     78: "Cirneco Dell'Etna",
     79: 'Clumber Spaniel',
     80: 'Cocker Spaniel',
     81: 'Collie',
     82: 'Coton De Tulear',
     83: 'Croatian Sheepdog',
     84: 'Curly-Coated Retriever',
     85: 'Czechoslovakian Vlack',
     86: 'Dachshund',
     87: 'Dalmatian',
     88: 'Dandie Dinmont Terrier',
     89: 'Danish-Swedish Farmdog',
     90: 'Deutscher Wachtelhund',
     91: 'Doberman Pinscher',
     92: 'Dogo Argentino',
     93: 'Dogue de Bordeaux',
     94: 'Drentsche Patrijshond',
     95: 'Drever',
     96: 'Dutch Shepherd',
     97: 'English Cocker Spaniel',
     98: 'English Foxhound',
     99: 'English Setter',
     100: 'English Shepherd',
     101: 'English Springer Spaniel',
     102: 'English Toy Spaniel',
     103: 'Entlebucher Mountain Dog',
     104: 'Estrela Mountain Dog',
     105: 'Eurasier',
     106: 'Field Spaniel',
     107: 'Finish Spitz',
     108: 'Finnish Lapphund',
     109: 'Flat-Coated Retriever',
     110: 'French Bulldog',
     111: 'French Spaniel',
     112: 'German Longhaired Pointer',
     113: 'German Pinscher',
     114: 'German Shepherd Dog',
     115: 'German Shorthaired Pointer',
     116: 'German Spitz',
     117: 'German Wirehaired Pointer',
     118: 'Giant Schnauzer',
     119: 'Glen of Imaal Terrier',
     120: 'Golden Retriever',
     121: 'Gordon Setter',
     122: 'Grand Basset Griffon Vendeen',
     123: 'Great Dane',
     124: 'Great Pyrenees',
     125: 'Greater Swiss Mountain Dog',
     126: 'Greyhound',
     127: 'Hamiltonstovare',
     128: 'Hanoverian Scenthound',
     129: 'Harrier',
     130: 'Havanese',
     131: 'Hokkaido',
     132: 'Hovawart',
     133: 'Ibizan Hound',
     134: 'Icelandic Sheepdog',
     135: 'Irish Red and White Setter',
     136: 'Irish Setter',
     137: 'Irish Terrier',
     138: 'Irish Water Spaniel',
     139: 'Irish Wolfhound',
     140: 'Italian Greyhound',
     141: 'Jack Russell Terrier',
     142: 'Jagdterrier',
     143: 'Japanese Chin',
     144: 'Jindo',
     145: 'Kai Ken',
     146: 'Karelian Bear Dog',
     147: 'Keeshond',
     148: 'Kerry Blue Terrier',
     149: 'Kishu Ken',
     150: 'Komondor',
     151: 'Kromfohrlander',
     152: 'Kuvasz',
     153: 'Labrador Retriever',
     154: 'Lagotto Romagnolo',
     155: 'Lakeland Terrier',
     156: 'Lancashire Heeler',
     157: 'Lapponian Herder',
     158: 'Leonberger',
     159: 'Lhasa Apso',
     160: 'Lowchen',
     161: 'Maltese',
     162: 'Manchester Terrier',
     163: 'Mastiff',
     164: 'Miniature American Shepherd',
     165: 'Miniature Bull Terrier',
     166: 'Miniature Pinscher',
     167: 'Miniature Schnauzer',
     168: 'Mountain Cur',
     169: 'Mudi',
     170: 'Neapolitan Mastiff',
     171: 'Nederlandse Kooikerhondje',
     172: 'Newfoundland',
     173: 'Norfolk Terrier',
     174: 'Norrbottenspets',
     175: 'Norwegian Buhund',
     176: 'Norwegian Elkhound',
     177: 'Norwegian Lundhund',
     178: 'Norwich Terrier',
     179: 'Nova Scotia Duck Tolling Retriever',
     180: 'Old English Sheepdog',
     181: 'Otterhound',
     182: 'Papillon',
     183: 'Parson Russell Terrier',
     184: 'Pekingese',
     185: 'Pembroke Welsh Corgi',
     186: 'Perro de Presa Canario',
     187: 'Peruvian Inca Orchid',
     188: 'Petit Basset Griffon Vendeen',
     189: 'Pharaoh Hound',
     190: 'Plott',
     191: 'Pointer',
     192: 'Polish Lowland Sheepdog',
     193: 'Pomeranian',
     194: 'Poodle',
     195: 'Poodle (Toy)',
     196: 'Porcelaine',
     197: 'Portuguese Podengo',
     198: 'Portuguese Podengo Pequeno',
     199: 'Portuguese Pointer',
     200: 'Portuguese Sheepdog',
     201: 'Portuguese Water Dog',
     202: 'Pudelpointer',
     203: 'Pug',
     204: 'Puli',
     205: 'Pumi',
     206: 'Pyrenean Mastiff',
     207: 'Pyrenean Shepherd',
     208: 'Rafeiro de Alentejo',
     209: 'Rat Terrier',
     210: 'Redbone Coonhound',
     211: 'Rhodesian Ridgeback',
     212: 'Romanian Mioritic Shepherd Dog',
     213: 'Rottweiler',
     214: 'Russell Terrier',
     215: 'Russian Toy',
     216: 'Russian Tsvetnaya Bolonka',
     217: 'Saluki',
     218: 'Samoyed',
     219: 'Schapendoes',
     220: 'Schipperke',
     221: 'Scottish Deerhound',
     222: 'Scottish Terrier',
     223: 'Sealyham Terrier',
     224: 'Segugio Italiano',
     225: 'Shetland Sheepdog',
     226: 'Shiba Inu',
     227: 'Shih Tzu',
     228: 'Shikoku',
     229: 'Siberian Husky',
     230: 'Silken Windhound',
     231: 'Silky Terrier',
     232: 'Skye Terrier',
     233: 'Sloughi',
     234: 'Slovakian Wirehaired Pointer',
     235: 'Slovensky Cuvac',
     236: 'Slovensky Kopov',
     237: 'Small Musterlander Pointer',
     238: 'Smooth Fox Terrier',
     239: 'Soft Coated Wheaten Terrier',
     240: 'Spanish Mastiff',
     241: 'Spanish Water Dog',
     242: 'Spinone Italiano',
     243: 'St. Bernard',
     244: 'Stabyhoun',
     245: 'Staffordshire Bull Terrier',
     246: 'Standard Schnauzer',
     247: 'Sussex Spaniel',
     248: 'Swedish Lapphund',
     249: 'Swedish Vallhund',
     250: 'Taiwan Dog',
     251: 'Teddy Roosevelt Terrier',
     252: 'Thai Ridgeback',
     253: 'Tibetan Mastiff',
     254: 'Tibetan Spaniel',
     255: 'Tibetan Terrier',
     256: 'Tornjak',
     257: 'Tosa',
     258: 'Toy Fox Terrier',
     259: 'Transylvanian Hound',
     260: 'Treeing Tennessee Brindle',
     261: 'Treeing Walker Coonhound',
     262: 'Village Dog',
     263: 'Vizsla',
     264: 'Weimaraner',
     265: 'Welsh Springer Spaniel',
     266: 'Welsh Terrier',
     267: 'West Highland White Terrier',
     268: 'Whippet',
     269: 'Wire Fox Terrier',
     270: 'Wirehaired Pointing Griffon',
     271: 'Wirehaired Vizsla',
     272: 'Wolf',
     273: 'Working Kelpie',
     274: 'Xoloitzcuintli',
     275: 'Yakutian Laika',
     276: 'Yorkshire Terrier',
     277: 'My dog is a non-AKC purebred not listed here'
}

In [15]:
df["afus_dd_fns_sire_breed"]

0       NaN
1       NaN
2       NaN
3       NaN
4       NaN
         ..
15715   NaN
15716   NaN
15717   NaN
15718   NaN
15719   NaN
Name: afus_dd_fns_sire_breed, Length: 15720, dtype: float64